#!/usr/bin/env node

/**
 * Run this script (from root directory): node scripts/lint
 *
 * This runs tests for all sample solutions
 */

const shell = require('shelljs');
const helpers = require('./helpers');
const assignment = shell.env['ASSIGNMENT'];

const infoStr =
    assignment ? '\nRunning lint for ' + assignment + '...':
    '\nRunning lint for all exercises...';
const failureStr = 'Lint check failed!';
helpers.prepareAndRun('npx eslint tmp_exercises', infoStr, failureStr);
