#!/usr/bin/env node

/**
 * Run this script (from root directory): npx babel-node scripts/name-uniq
 *
 * This will run following checks:
 *
 * 1. All exercises have unique package names in their package.json files.
 */

const shell = require('shelljs');
const { packageFiles, registerExitHandler } = require('./helpers');

registerExitHandler();

const allNames = packageFiles.map(
  (filePath) => JSON.parse(shell.cat(filePath).toString())['name']
);

// Check if all exercises have unique package names
const duplicates = allNames.filter((e, i) => allNames.indexOf(e) !== i);

if (duplicates.length !== 0) {
  shell.echo(
    `[Failure] Duplicate package names found: ${duplicates.join(', ')}`
  );
  shell.exit(1);
}

shell.echo('[Success] All package names are unique.');
shell.exit(0);
