#!/usr/bin/env node

/**
 * Run this script (from root directory): node scripts/test
 *
 * This runs eslint on all sample solutions (and test) files
 */

var shell = require('shelljs');
var helpers = require('./helpers');
var assignment = shell.env['ASSIGNMENT'];

var infoStr =
    assignment ? '\nRunning tests for ' + assignment + '...':
    '\nRunning tests for all exercises...';
var failureStr = 'Tests failed!';
helpers.prepareAndRun('npx jest --bail tmp_exercises', infoStr, failureStr);
