#!/usr/bin/env node

var shell = require('shelljs');
var helpers = require('./helpers');
var assignment = shell.env['ASSIGNMENT'];

var infoStr =
    assignment ? '\nRunning tests for ' + assignment + '...':
    '\nRunning tests for all exercises...';
var failureStr = 'Tests failed!';
helpers.prepareAndRun('npx jest --bail tmp_exercises', infoStr, failureStr);
